### ISSUE TITLE
License statement

### ISSUE THREAD

**Issue by wget** [rodcorsi/mattermosti18n#3]
Hi there,

Could you please add a license file to your project?

We need such an information in order for your package to be integrated in repositories like [AUR](https://wiki.archlinux.org/index.php/Arch_User_Repository).

Thanks in advance :)

**Comment by rodcorsi** [comment]
I added MIT license thank you  ;)

**Comment by wget** [comment]
@rodcorsi Great thanks :) 
Btw, if you could add this statement as repository description : `A tool for Mattermost used to convert translations between GNU gettext .po and JSON files`
That way, I can publish my Arch Linux package now :)

**Comment by rodcorsi** [comment]
:+1:
